### ISSUE TITLE
Breaking build in go1.10.4

### ISSUE THREAD

**Issue by PFadel** [centrifugal/gocent#8]
Hello,

Starting today, we are getting this error in our CI builds that use this client:

```bash
centrifugal/gocent/main.go:57:17: unknown field 'MaxConnsPerHost' in struct literal of type http.Transport
```

I believe it's because [this was added](https://github.com/centrifugal/gocent/pull/6/files#diff-7ddfb3e035b42cd70649cc33393fe32cR57).

I also believe this field is was [very recently added](https://golang.org/doc/go1.11#net/http).

We are still using go1.10.4 and we were not planning to update for go1.11.

Is there a way to solve this issue ? Or we'll need to update our go version ?
Any help would be appreciated.

We love centrifugo btw.

**Comment by FZambia** [comment]
Hello, looks like you are not using versioning in your builds. This is always not a good idea. Today we migrated client to support Centrifugo v2 with breaking changes and created v2.0.0 tag. You have to use v1.0.0 tag - https://github.com/centrifugal/gocent/tree/v1.0.0

Though it's a bit surprising for me that `MaxConnsPerHost` not available before go1.11, maybe we should continue support of go1.10.x in v2 too. 

Thanks for your kind words about Centrifugo:)

**Comment by PFadel** [comment]
Yeah, I agree that we should use versioning but it's a legacy API that we do want to put much effort in it, we rarely even execute those builds.

We are thinking in just running the builds with go1.11, but if you guys could add support to go1.10.x it would be great too. (:

**Comment by FZambia** [comment]
You just need to use gocent v1.0.0 now - it works with Centrifugo v1 and with go 1.10.x, so you don't need to update anything.

v2.0.0 works with Centrifugo v2 only, it's not compatible with Centrifugo v1.

**Comment by biancarosa** [comment]
We're trying to change the import to use gopkg.in (
https://gopkg.in/centrifugal/gocent.v1) right now, but we cannot use the currently version tagged as v1.0.0 due to the [import path checking](https://golang.org/cmd/go/#hdr-Import_path_checking).

`package gocent // import "github.com/centrifugal/gocent"`.

**Comment by FZambia** [comment]
Just created version 1.0.1 without canonical import path - this should resolve problem with gopkg.in, please try it

**Comment by PFadel** [comment]
@FZambia it worked!

Thank you.
